SKILL_TAXONOMY = {
    # Programming Languages
    "python": "Python",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "java": "Java",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "csharp": "C#",
    "php": "PHP",
    "ruby": "Ruby",
    "golang": "Go",
    "rust": "Rust",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "dart": "Dart",
    "scala": "Scala",
    "perl": "Perl",
    "r": "R",
    "matlab": "MATLAB",
    "shell": "Shell Scripting",
    "bash": "Bash",
    "powershell": "PowerShell",
    "sql": "SQL",
    "html": "HTML5",
    "html5": "HTML5",
    "css": "CSS3",
    "css3": "CSS3",
    "sass": "Sass/SCSS",
    "scss": "Sass/SCSS",

    # Web and Mobile Frameworks
    "react": "React",
    "react.js": "React",
    "reactjs": "React",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "vue": "Vue.js",
    "vue.js": "Vue.js",
    "vuejs": "Vue.js",
    "nuxt": "Nuxt.js",
    "angular": "Angular",
    "angularjs": "Angular",
    "svelte": "Svelte",
    "sveltekit": "SvelteKit",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "express": "Express.js",
    "express.js": "Express.js",
    "nest.js": "NestJS",
    "nestjs": "NestJS",
    "django": "Django",
    "fastapi": "FastAPI",
    "flask": "Flask",
    "spring": "Spring Framework",
    "spring boot": "Spring Boot",
    "asp.net": "ASP.NET",
    ".net": ".NET",
    "dot net": ".NET",
    "laravel": "Laravel",
    "ruby on rails": "Ruby on Rails",
    "rails": "Ruby on Rails",
    "flutter": "Flutter",
    "react native": "React Native",
    "android sdk": "Android SDK",
    "ios": "iOS Development",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "graphql": "GraphQL",
    "rest api": "RESTful APIs",
    "restful": "RESTful APIs",
    "grpc": "gRPC",
    "websockets": "WebSockets",
    "microservices": "Microservices",

    # AI, ML, NLP and Data Science
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "artificial intelligence": "Artificial Intelligence",
    "nlp": "Natural Language Processing (NLP)",
    "natural language processing": "Natural Language Processing (NLP)",
    "computer vision": "Computer Vision",
    "opencv": "OpenCV",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "keras": "Keras",
    "scikit-learn": "Scikit-Learn",
    "sklearn": "Scikit-Learn",
    "huggingface": "Hugging Face",
    "transformers": "Transformers",
    "bert": "BERT",
    "distilbert": "DistilBERT",
    "llm": "Large Language Models (LLMs)",
    "large language models": "Large Language Models (LLMs)",
    "langchain": "LangChain",
    "llamaindex": "LlamaIndex",
    "rag": "RAG (Retrieval-Augmented Generation)",
    "fine-tuning": "Fine-Tuning",
    "generative ai": "Generative AI",
    "genai": "Generative AI",
    "prompt engineering": "Prompt Engineering",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "spacy": "spaCy",
    "nltk": "NLTK",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "data analysis": "Data Analysis",
    "data visualization": "Data Visualization",
    "data mining": "Data Mining",
    "data engineering": "Data Engineering",
    "etl": "ETL Pipelines",
    "data pipeline": "Data Pipelines",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",

    # Cloud, DevOps and Infrastructure
    "aws": "AWS (Amazon Web Services)",
    "amazon web services": "AWS",
    "azure": "Microsoft Azure",
    "gcp": "Google Cloud Platform (GCP)",
    "google cloud": "Google Cloud Platform (GCP)",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI/CD",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "linux": "Linux",
    "nginx": "Nginx",
    "apache": "Apache",
    "serverless": "Serverless",
    "aws lambda": "AWS Lambda",
    "s3": "AWS S3",
    "ec2": "AWS EC2",
    "cloud computing": "Cloud Computing",
    "prometheus": "Prometheus",
    "grafana": "Grafana",

    # Databases and Big Data
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "sqlite": "SQLite",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "cassandra": "Apache Cassandra",
    "dynamodb": "DynamoDB",
    "oracle": "Oracle DB",
    "ms sql": "MS SQL Server",
    "sql server": "MS SQL Server",
    "neo4j": "Neo4j",
    "firebase": "Firebase",
    "supabase": "Supabase",
    "pinecone": "Pinecone",
    "weaviate": "Weaviate",
    "chromadb": "ChromaDB",
    "qdrant": "Qdrant",
    "apache spark": "Apache Spark",
    "spark": "Apache Spark",
    "pyspark": "PySpark",
    "hadoop": "Hadoop",
    "kafka": "Apache Kafka",
    "snowflake": "Snowflake",
    "bigquery": "Google BigQuery",
    "databricks": "Databricks",

    # Methodologies, Version Control and Testing
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "jira": "Jira",
    "confluence": "Confluence",
    "agile": "Agile Methodologies",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "unit testing": "Unit Testing",
    "tdd": "TDD (Test-Driven Development)",
    "pytest": "PyTest",
    "jest": "Jest",
    "cypress": "Cypress",
    "selenium": "Selenium",
    "postman": "Postman",
    "figma": "Figma",

    # Soft Skills and Leadership
    "leadership": "Leadership",
    "project management": "Project Management",
    "product management": "Product Management",
    "team collaboration": "Team Collaboration",
    "communication": "Effective Communication",
    "problem solving": "Problem Solving",
    "critical thinking": "Critical Thinking",
    "time management": "Time Management",
    "mentoring": "Mentoring and Coaching",
    "stakeholder management": "Stakeholder Management",
    "client communication": "Client Relations",
    "negotiation": "Negotiation",
    "strategic planning": "Strategic Planning"
}
